"""
Server-rendered routes — generated by scripts/scaffold_htmx.py --style plain

Edit freely.  Re-run the scaffold to regenerate from scratch (use --force).

Pattern: every form POSTs to a mutation endpoint which redirects back to
GET /app/ — the single page that renders everything.
"""

from fastapi import APIRouter, Form, Request
from fastapi.responses import HTMLResponse, RedirectResponse
from fastapi.templating import Jinja2Templates
from piccolo.apps.user.tables import BaseUser
from piccolo_api.session_auth.tables import SessionsBase
from starlette.status import HTTP_303_SEE_OTHER

from auth_helpers import clear_session_cookie, get_authenticated_user, set_session_cookie
from tables import Category, Todo

router = APIRouter(prefix="/app")
templates = Jinja2Templates(directory="templates")


# ---------------------------------------------------------------------------
# Shared helper
# ---------------------------------------------------------------------------

async def _app_context(user: BaseUser) -> dict:
    """Fetch all data needed to render the page."""
    ctx: dict = {"user": user}
    ctx["categories"] = await Category.select()
    ctx["todos"] = await Todo.select(Todo.all_columns(), Todo.category._.name).where(Todo.user == user.id)
    return ctx


# ---------------------------------------------------------------------------
# GET /app/  — renders everything on one page
# ---------------------------------------------------------------------------

@router.get("/", response_class=HTMLResponse)
async def app_index(request: Request):
    user = await get_authenticated_user(request)
    ctx = await _app_context(user) if user else {"user": None}
    return templates.TemplateResponse(request, "app/page.html", ctx)


# ---------------------------------------------------------------------------
# Auth
# ---------------------------------------------------------------------------

@router.post("/login")
async def app_login(request: Request, username: str = Form(...), password: str = Form(...)):
    user_id = await BaseUser.login(username=username, password=password)
    if not user_id:
        # Re-render login page with error message
        return templates.TemplateResponse(request, "app/page.html",
            {"user": None, "error": "Invalid username or password"}, status_code=401)
    session = await SessionsBase.create_session(user_id=user_id)
    response = RedirectResponse("/app/", status_code=HTTP_303_SEE_OTHER)
    set_session_cookie(response=response, token=session.token)
    return response

@router.post("/logout")
async def app_logout(request: Request):
    token = request.cookies.get("id")
    if token:
        await SessionsBase.remove_session(token=token)
    response = RedirectResponse("/app/", status_code=HTTP_303_SEE_OTHER)
    clear_session_cookie(response)
    return response


# ---------------------------------------------------------------------------
# Todo
# ---------------------------------------------------------------------------

@router.post("/todos")
async def app_create_todo(request: Request, task: str = Form(...), category: int = Form(...), done: bool = Form(False)):
    user = await get_authenticated_user(request)
    if not user: return RedirectResponse("/app/", status_code=HTTP_303_SEE_OTHER)
    await Todo.insert(Todo(task=task, user=user.id, category=category, done=done))
    return RedirectResponse("/app/", status_code=HTTP_303_SEE_OTHER)

@router.post("/todos/{item_id}/toggle_done")
async def app_toggle_todo_done(request: Request, item_id: int):
    user = await get_authenticated_user(request)
    if not user: return RedirectResponse("/app/", status_code=HTTP_303_SEE_OTHER)
    item = await Todo.objects().where((Todo.id == item_id) & (Todo.user == user.id)).first()
    if item:
        await Todo.update({Todo.done: not item.done}).where((Todo.id == item_id) & (Todo.user == user.id))
    return RedirectResponse("/app/", status_code=HTTP_303_SEE_OTHER)

@router.post("/todos/{item_id}/delete")
async def app_delete_todo(request: Request, item_id: int):
    user = await get_authenticated_user(request)
    if not user: return RedirectResponse("/app/", status_code=HTTP_303_SEE_OTHER)
    await Todo.delete().where((Todo.id == item_id) & (Todo.user == user.id))
    return RedirectResponse("/app/", status_code=HTTP_303_SEE_OTHER)
