"""
HTMX frontend routes — generated by scripts/scaffold_htmx.py

Edit freely.  Re-run the scaffold to regenerate from scratch (use --force).
"""

from fastapi import APIRouter, Form, Request
from fastapi.responses import HTMLResponse, Response
from fastapi.templating import Jinja2Templates
from piccolo.apps.user.tables import BaseUser
from piccolo_api.session_auth.tables import SessionsBase

from auth_helpers import clear_session_cookie, get_authenticated_user, set_session_cookie
from tables import Category, Todo

router = APIRouter(prefix="/htmx")
templates = Jinja2Templates(directory="templates")


# ---------------------------------------------------------------------------
# Shared helper
# ---------------------------------------------------------------------------

async def _app_context(user: BaseUser) -> dict:
    """Fetch all data needed to render the app shell."""
    ctx: dict = {"user": user}
    ctx["categories"] = await Category.select()
    ctx["todos"] = await Todo.select(Todo.all_columns(), Todo.category._.name).where(Todo.user == user.id)
    return ctx


# ---------------------------------------------------------------------------
# GET /htmx  — full page
# ---------------------------------------------------------------------------

@router.get("/", response_class=HTMLResponse)
async def htmx_index(request: Request):
    user = await get_authenticated_user(request)
    ctx = await _app_context(user) if user else {"user": None}
    return templates.TemplateResponse(request, "htmx/page.html", ctx)


# ---------------------------------------------------------------------------
# Auth
# ---------------------------------------------------------------------------

@router.post("/login")
async def htmx_login(request: Request, username: str = Form(...), password: str = Form(...)):
    user_id = await BaseUser.login(username=username, password=password)
    if not user_id:
        return templates.TemplateResponse(request, "htmx/_login.html",
            {"error": "Invalid username or password"}, status_code=401)
    session = await SessionsBase.create_session(user_id=user_id)
    response = Response(status_code=204, headers={"HX-Redirect": "/htmx/"})
    set_session_cookie(response=response, token=session.token)
    return response

@router.post("/logout")
async def htmx_logout(request: Request):
    token = request.cookies.get("id")
    if token:
        await SessionsBase.remove_session(token=token)
    response = Response(status_code=204, headers={"HX-Redirect": "/htmx/"})
    clear_session_cookie(response)
    return response


# ---------------------------------------------------------------------------
# Todo
# ---------------------------------------------------------------------------

@router.post("/todos", response_class=HTMLResponse)
async def htmx_create_todo(request: Request, task: str = Form(...), category: int = Form(...), done: bool = Form(False)):
    user = await get_authenticated_user(request)
    if not user: return HTMLResponse("Unauthorised", status_code=401)
    await Todo.insert(Todo(task=task, user=user.id, category=category, done=done))
    ctx = await _app_context(user)
    return templates.TemplateResponse(request, "htmx/_todo_table.html", ctx)

@router.get("/todos", response_class=HTMLResponse)
async def htmx_list_todo(request: Request):
    user = await get_authenticated_user(request)
    if not user: return HTMLResponse("Unauthorised", status_code=401)
    ctx = await _app_context(user)
    return templates.TemplateResponse(request, "htmx/_todo_table.html", ctx)

@router.post("/todos/{item_id}/toggle_done", response_class=HTMLResponse)
async def htmx_toggle_todo_done(request: Request, item_id: int):
    user = await get_authenticated_user(request)
    if not user: return HTMLResponse("Unauthorised", status_code=401)
    item = await Todo.objects().where((Todo.id == item_id) & (Todo.user == user.id)).first()
    if item:
        await Todo.update({Todo.done: not item.done}).where((Todo.id == item_id) & (Todo.user == user.id))
    ctx = await _app_context(user)
    return templates.TemplateResponse(request, "htmx/_todo_table.html", ctx)

@router.delete("/todos/{item_id}", response_class=HTMLResponse)
async def htmx_delete_todo(request: Request, item_id: int):
    user = await get_authenticated_user(request)
    if not user: return HTMLResponse("Unauthorised", status_code=401)
    await Todo.delete().where((Todo.id == item_id) & (Todo.user == user.id))
    ctx = await _app_context(user)
    return templates.TemplateResponse(request, "htmx/_todo_table.html", ctx)
