"""
scaffold_htmx.py
================
Generates a starter server-rendered frontend from your Piccolo table definitions.

Usage (run from the project root):
    python scripts/scaffold_htmx.py                  # plain Jinja2 (default)
    python scripts/scaffold_htmx.py --style htmx     # HTMX partial-swap version

Styles
------
  plain (default)
    Pure HTML forms + Post/Redirect/Get.  No JavaScript required.
    Every form posts to the server; the server redirects back to the page.
    Best for teaching HTML/Python before introducing client-side concepts.

  htmx
    Same routes but mutations return HTML fragments that HTMX swaps in-place.
    Requires htmx.min.js (served from /static/).
    Feels more "modern app" without a full JavaScript framework.

Both styles share the same Piccolo introspection logic and produce the same
editable starting-point files.  Re-running will NOT overwrite files unless you
pass --force.

Options:
  --style         plain (default) or htmx
  --prefix        URL prefix for the router (default: /app for plain, /htmx for htmx)
  --force         Overwrite existing generated files
  --tables-mod    Python module to introspect (default: tables)
  --out-routes    Output path for the routes file (default: app_routes.py / htmx_routes.py)
  --out-templates Output directory for templates (default: templates/app / templates/htmx)
"""

import argparse
import importlib
import inspect
import sys
import textwrap
from pathlib import Path

from piccolo.columns import Boolean, ForeignKey, Serial
from piccolo.table import Table


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def discover_tables(module) -> list[type[Table]]:
    """Return all non-abstract Piccolo Table subclasses defined in module."""
    tables = []
    for _, obj in inspect.getmembers(module, inspect.isclass):
        if (
            issubclass(obj, Table)
            and obj is not Table
            and obj.__module__ == module.__name__
        ):
            tables.append(obj)
    return tables


def user_columns(table: type[Table]):
    """Return columns excluding the primary key (Serial)."""
    return [c for c in table._meta.columns if not isinstance(c, Serial)]


def col_name(col) -> str:
    return col._meta.name


def fk_ref(col) -> type[Table] | None:
    """Return the referenced Table class for a ForeignKey column, or None."""
    if not isinstance(col, ForeignKey):
        return None
    return col._foreign_key_meta.references


def label(name: str) -> str:
    """Turn snake_case into Title Case for display."""
    return name.replace("_", " ").title()


def plural(name: str) -> str:
    if name.endswith("y"):
        return name[:-1] + "ies"
    if name.endswith("s"):
        return name + "es"
    return name + "s"


def is_user_data(t: type[Table], all_tables: dict[str, type[Table]], visited: set | None = None) -> bool:
    """Return True if this table is directly or transitively owned by BaseUser.

    Examples:
      Todo(user=FK(BaseUser))         → True  (direct)
      Measurement(survey=FK(Survey))
        where Survey(user=FK(BaseUser)) → True  (transitive)
      Category(name=Varchar)          → False (pure lookup, no path to BaseUser)
    """
    if visited is None:
        visited = set()
    if t.__name__ in visited:
        return False  # avoid cycles
    visited.add(t.__name__)
    for col in user_columns(t):
        ref = fk_ref(col)
        if ref is None:
            continue
        if ref.__name__ == "BaseUser":
            return True
        # Check if the referenced table is itself user-owned
        if ref.__name__ in all_tables and is_user_data(ref, all_tables, visited):
            return True
    return False


# ---------------------------------------------------------------------------
# Code generators
# ---------------------------------------------------------------------------

def gen_routes(tables: list[type[Table]]) -> str:
    """Generate htmx_routes.py content."""

    # Collect all referenced foreign tables (excluding BaseUser) so we can
    # import them and pre-load their rows for select dropdowns.
    fk_refs: dict[str, type[Table]] = {}
    for t in tables:
        for col in user_columns(t):
            ref = fk_ref(col)
            if ref and ref.__name__ != "BaseUser":
                fk_refs[ref.__name__] = ref

    all_tables = {t.__name__: t for t in tables}
    all_tables.update(fk_refs)

    import_names = sorted(all_tables.keys())

    lines: list[str] = []

    lines.append('"""')
    lines.append("HTMX frontend routes — generated by scripts/scaffold_htmx.py")
    lines.append("")
    lines.append("Edit freely.  Re-run the scaffold to regenerate from scratch (use --force).")
    lines.append('"""')
    lines.append("")
    lines.append("from fastapi import APIRouter, Form, Request")
    lines.append("from fastapi.responses import HTMLResponse, Response")
    lines.append("from fastapi.templating import Jinja2Templates")
    lines.append("from piccolo.apps.user.tables import BaseUser")
    lines.append("from piccolo_api.session_auth.tables import SessionsBase")
    lines.append("")
    lines.append("from auth_helpers import clear_session_cookie, get_authenticated_user, set_session_cookie")
    lines.append(f"from tables import {', '.join(import_names)}")
    lines.append("")
    lines.append("router = APIRouter(prefix=\"/htmx\")")
    lines.append("templates = Jinja2Templates(directory=\"templates\")")
    lines.append("")

    # ---- shared helper to render the app shell ----
    lines.append("")
    lines.append("# ---------------------------------------------------------------------------")
    lines.append("# Shared helper")
    lines.append("# ---------------------------------------------------------------------------")
    lines.append("")
    lines.append("async def _app_context(user: BaseUser) -> dict:")
    lines.append('    """Fetch all data needed to render the app shell."""')
    lines.append("    ctx: dict = {\"user\": user}")

    # Collect names already added to avoid duplicates
    added: set[str] = set()

    # FK reference tables first (so they're available for dropdowns)
    for ref_name, ref_cls in fk_refs.items():
        var = plural(ref_name.lower())
        lines.append(f"    ctx[\"{var}\"] = await {ref_name}.select()")
        added.add(ref_name)

    for t in tables:
        var = plural(t.__name__.lower())
        cols = user_columns(t)
        fk_cols = [c for c in cols if fk_ref(c) and fk_ref(c).__name__ != "BaseUser"]
        user_fk_cols = [c for c in cols if fk_ref(c) and fk_ref(c).__name__ == "BaseUser"]
        all_tables_map = {t.__name__: t for t in tables}
        if user_fk_cols:
            # Directly owned — filter by user FK
            where_clause = f".where({t.__name__}.{col_name(user_fk_cols[0])} == user.id)"
        elif is_user_data(t, all_tables_map):
            # Transitively owned — student should add filtering via parent FK
            where_clause = "  # TODO: filter by owner, e.g. .where(...)"
        else:
            where_clause = ""
        if fk_cols:
            join_args = ", ".join(f"{t.__name__}.{col_name(c)}._.name" for c in fk_cols)
            lines.append(f"    ctx[\"{var}\"] = await {t.__name__}.select({t.__name__}.all_columns(), {join_args}){where_clause}")
        elif t.__name__ not in added:
            lines.append(f"    ctx[\"{var}\"] = await {t.__name__}.select(){where_clause}")

    lines.append("    return ctx")
    lines.append("")

    # ---- full page ----
    lines.append("")
    lines.append("# ---------------------------------------------------------------------------")
    lines.append("# GET /htmx  — full page")
    lines.append("# ---------------------------------------------------------------------------")
    lines.append("")
    lines.append("@router.get(\"/\", response_class=HTMLResponse)")
    lines.append("async def htmx_index(request: Request):")
    lines.append("    user = await get_authenticated_user(request)")
    lines.append("    ctx = await _app_context(user) if user else {\"user\": None}")
    lines.append("    return templates.TemplateResponse(request, \"htmx/page.html\", ctx)")
    lines.append("")

    # ---- login / logout ----
    lines.append("")
    lines.append("# ---------------------------------------------------------------------------")
    lines.append("# Auth")
    lines.append("# ---------------------------------------------------------------------------")
    lines.append("")
    lines.append("@router.post(\"/login\")")
    lines.append("async def htmx_login(request: Request, username: str = Form(...), password: str = Form(...)):")
    lines.append("    user_id = await BaseUser.login(username=username, password=password)")
    lines.append("    if not user_id:")
    lines.append("        return templates.TemplateResponse(request, \"htmx/_login.html\",")
    lines.append("            {\"error\": \"Invalid username or password\"}, status_code=401)")
    lines.append("    session = await SessionsBase.create_session(user_id=user_id)")
    lines.append("    response = Response(status_code=204, headers={\"HX-Redirect\": \"/htmx/\"})")
    lines.append("    set_session_cookie(response=response, token=session.token)")
    lines.append("    return response")
    lines.append("")
    lines.append("@router.post(\"/logout\")")
    lines.append("async def htmx_logout(request: Request):")
    lines.append("    token = request.cookies.get(\"id\")")
    lines.append("    if token:")
    lines.append("        await SessionsBase.remove_session(token=token)")
    lines.append("    response = Response(status_code=204, headers={\"HX-Redirect\": \"/htmx/\"})")
    lines.append("    clear_session_cookie(response)")
    lines.append("    return response")
    lines.append("")

    # ---- per-table CRUD (for all user-data tables: direct or transitive BaseUser ownership) ----
    all_tables_map = {t.__name__: t for t in tables}
    owned_tables = [t for t in tables if is_user_data(t, all_tables_map)]
    for t in owned_tables:
        tname = t.__name__
        tvar = tname.lower()
        tplural = plural(tvar)
        cols = user_columns(t)
        bool_cols = [c for c in cols if isinstance(c, Boolean)]
        fk_cols = [c for c in cols if fk_ref(c) and fk_ref(c).__name__ != "BaseUser"]
        # columns to include in create form (no FK to BaseUser, no bool toggle on create)
        create_cols = [c for c in cols if fk_ref(c) is None or fk_ref(c).__name__ != "BaseUser"]

        lines.append("")
        lines.append("# ---------------------------------------------------------------------------")
        lines.append(f"# {tname}")
        lines.append("# ---------------------------------------------------------------------------")
        lines.append("")

        # create
        form_params = ", ".join(
            f"{col_name(c)}: int = Form(...)" if isinstance(c, ForeignKey) else
            f"{col_name(c)}: bool = Form(False)" if isinstance(c, Boolean) else
            f"{col_name(c)}: str = Form(...)"
            for c in create_cols
        )
        new_obj_args = ", ".join(
            f"{col_name(c)}={col_name(c)}" for c in create_cols
        )
        lines.append(f"@router.post(\"/{tplural}\", response_class=HTMLResponse)")
        lines.append(f"async def htmx_create_{tvar}(request: Request, {form_params}):")
        lines.append(f"    user = await get_authenticated_user(request)")
        lines.append(f"    if not user: return HTMLResponse(\"Unauthorised\", status_code=401)")
        lines.append(f"    await {tname}.insert({tname}({new_obj_args}))")
        lines.append(f"    ctx = await _app_context(user)")
        lines.append(f"    return templates.TemplateResponse(request, \"htmx/_{tvar}_table.html\", ctx)")
        lines.append("")
        # list (GET) — called on page load by HTMX hx-trigger="load"
        lines.append(f'@router.get("/{tplural}", response_class=HTMLResponse)')
        lines.append(f"async def htmx_list_{tvar}(request: Request):")
        lines.append(f"    user = await get_authenticated_user(request)")
        lines.append(f"    if not user: return HTMLResponse(\"Unauthorised\", status_code=401)")
        lines.append(f"    ctx = await _app_context(user)")
        lines.append(f"    return templates.TemplateResponse(request, \"htmx/_{tvar}_table.html\", ctx)")
        lines.append("")
        # toggle (only if there are boolean columns)
        for bc in bool_cols:
            bcn = col_name(bc)
            lines.append(f"@router.post(\"/{tplural}/{{item_id}}/toggle_{bcn}\", response_class=HTMLResponse)")
            lines.append(f"async def htmx_toggle_{tvar}_{bcn}(request: Request, item_id: int):")
            lines.append(f"    user = await get_authenticated_user(request)")
            lines.append(f"    if not user: return HTMLResponse(\"Unauthorised\", status_code=401)")
            lines.append(f"    item = await {tname}.objects().where({tname}.id == item_id).first()")
            lines.append(f"    if item:")
            lines.append(f"        await {tname}.update({{{tname}.{bcn}: not item.{bcn}}}).where({tname}.id == item_id)")
            lines.append(f"    ctx = await _app_context(user)")
            lines.append(f"    return templates.TemplateResponse(request, \"htmx/_{tvar}_table.html\", ctx)")
            lines.append("")

        # delete
        lines.append(f"@router.delete(\"/{tplural}/{{item_id}}\", response_class=HTMLResponse)")
        lines.append(f"async def htmx_delete_{tvar}(request: Request, item_id: int):")
        lines.append(f"    user = await get_authenticated_user(request)")
        lines.append(f"    if not user: return HTMLResponse(\"Unauthorised\", status_code=401)")
        lines.append(f"    await {tname}.delete().where({tname}.id == item_id)")
        lines.append(f"    ctx = await _app_context(user)")
        lines.append(f"    return templates.TemplateResponse(request, \"htmx/_{tvar}_table.html\", ctx)")
        lines.append("")

    return "\n".join(lines)


def gen_page_html(tables: list[type[Table]]) -> str:
    table_includes = "\n    ".join(
        f'{{% include "htmx/_{t.__name__.lower()}_table.html" %}}'
        for t in tables
    )
    return textwrap.dedent(f"""\
        <!DOCTYPE html>
        <html lang="en">
        <head>
          <meta charset="UTF-8" />
          <meta name="viewport" content="width=device-width, initial-scale=1.0" />
          <title>App</title>
          <script src="/static/htmx.min.js"></script>
          <style>
            body {{ font-family: sans-serif; max-width: 800px; margin: 2rem auto; padding: 0 1rem; }}
            table {{ width: 100%; border-collapse: collapse; margin-top: 1rem; }}
            th, td {{ text-align: left; padding: 0.4rem 0.6rem; border-bottom: 1px solid #ddd; }}
            th {{ background: #f4f4f4; }}
            .done {{ text-decoration: line-through; color: #888; }}
            .error {{ color: red; }}
            button {{ cursor: pointer; }}
          </style>
        </head>
        <body>
          {{% if user %}}
            {{% include "htmx/_app.html" %}}
          {{% else %}}
            {{% include "htmx/_login.html" %}}
          {{% endif %}}
        </body>
        </html>
    """)


def gen_login_html() -> str:
    return textwrap.dedent("""\
        <section id="login">
          <h2>Log in</h2>
          <form hx-post="/htmx/login" hx-target="#login" hx-swap="outerHTML">
            <div>
              <label>Username<br /><input name="username" type="text" required autofocus /></label>
            </div>
            <div style="margin-top:0.5rem">
              <label>Password<br /><input name="password" type="password" required /></label>
            </div>
            <div style="margin-top:0.75rem">
              <button type="submit">Log in</button>
            </div>
            {% if error %}<p class="error">{{ error }}</p>{% endif %}
          </form>
        </section>
    """)


def gen_app_html(tables: list[type[Table]], fk_refs: dict) -> str:
    """Generate _app.html with a create form and table section per table."""
    sections: list[str] = []

    sections.append("<section id=\"app\">")
    sections.append("  <p>")
    sections.append("    Logged in as <strong>{{ user.username }}</strong>")
    sections.append("    <button hx-post=\"/htmx/logout\" hx-confirm=\"Log out?\" style=\"margin-left:1rem\">Log out</button>")
    sections.append("  </p>")
    sections.append("")

    # Only render CRUD sections for user-data tables (direct or transitive BaseUser ownership).
    # Lookup tables like Category are managed via /admin — no frontend CRUD needed.
    all_tables_map = {t.__name__: t for t in tables}
    owned_tables = [t for t in tables if is_user_data(t, all_tables_map)]
    for t in owned_tables:
        tname = t.__name__
        tvar = tname.lower()
        tplural = plural(tvar)
        cols = user_columns(t)
        create_cols = [c for c in cols if fk_ref(c) is None or fk_ref(c).__name__ != "BaseUser"]

        sections.append(f"  <!-- ---- {tname} ---- -->")
        sections.append(f"  <h2>{label(tplural)}</h2>")
        sections.append("")
        sections.append(f"  <form hx-post=\"/htmx/{tplural}\" hx-target=\"#{tvar}-table\" hx-swap=\"outerHTML\"")
        sections.append(f"        hx-on::after-request=\"this.reset()\" style=\"display:flex;gap:0.5rem;flex-wrap:wrap;margin-bottom:1rem\">")

        for c in create_cols:
            cname = col_name(c)
            ref = fk_ref(c)
            if ref:
                ref_var = plural(ref.__name__.lower())
                sections.append(f"    <select name=\"{cname}\" required>")
                sections.append(f"      {{% for item in {ref_var} %}}")
                sections.append(f"        <option value=\"{{{{ item.id }}}}\">{{{{ item.name }}}}</option>")
                sections.append(f"      {{% endfor %}}")
                sections.append(f"    </select>")
            elif isinstance(c, Boolean):
                sections.append(f"    <label><input name=\"{cname}\" type=\"checkbox\" /> {label(cname)}</label>")
            else:
                sections.append(f"    <input name=\"{cname}\" type=\"text\" placeholder=\"{label(cname)}\" required />")

        sections.append(f"    <button type=\"submit\">Add {label(tvar)}</button>")
        sections.append(f"  </form>")
        sections.append("")
        sections.append(f"  <div id=\"{tvar}-table\" hx-get=\"/htmx/{tplural}\"")
        sections.append(f"       hx-trigger=\"load\" hx-swap=\"outerHTML\">")
        sections.append(f"    <p>Loading {tplural}…</p>")
        sections.append(f"  </div>")
        sections.append("")

    sections.append("</section>")
    return "\n".join(sections)


def gen_table_html(t: type[Table]) -> str:
    tname = t.__name__
    tvar = tname.lower()
    tplural = plural(tvar)
    cols = user_columns(t)
    bool_cols = [c for c in cols if isinstance(c, Boolean)]
    fk_cols = [c for c in cols if isinstance(c, ForeignKey) and fk_ref(c) and fk_ref(c).__name__ != "BaseUser"]
    display_cols = [c for c in cols if not isinstance(c, Boolean) and fk_ref(c) is None]

    lines = [f'<table id="{tvar}-table">']
    lines.append("  <thead><tr>")
    for c in display_cols:
        lines.append(f"    <th>{label(col_name(c))}</th>")
    for c in fk_cols:
        lines.append(f"    <th>{label(col_name(c))}</th>")
    for c in bool_cols:
        lines.append(f"    <th>{label(col_name(c))}</th>")
    lines.append("    <th></th>")
    lines.append("  </tr></thead>")
    lines.append(f"  <tbody>")
    lines.append(f"  {{% for item in {tvar}s %}}")
    lines.append("  <tr>")
    for c in display_cols:
        cname = col_name(c)
        lines.append(f"    <td>{{{{ item.{cname} }}}}</td>")
    for c in fk_cols:
        cname = col_name(c)
        lines.append(f"    <td>{{{{ item['{cname}.name'] or '—' }}}}</td>")
    for c in bool_cols:
        cname = col_name(c)
        lines.append(f"    <td>")
        lines.append(f"      <button hx-post=\"/htmx/{tplural}/{{{{ item.id }}}}/toggle_{cname}\"")
        lines.append(f"              hx-target=\"#{tvar}-table\" hx-swap=\"outerHTML\">")
        lines.append(f"        {{{{ '✅' if item.{cname} else '⬜' }}}}")
        lines.append(f"      </button>")
        lines.append(f"    </td>")
    lines.append(f"    <td>")
    lines.append(f"      <button hx-delete=\"/htmx/{tplural}/{{{{ item.id }}}}\"")
    lines.append(f"              hx-target=\"#{tvar}-table\" hx-swap=\"outerHTML\"")
    lines.append(f"              hx-confirm=\"Delete this {label(tvar)}?\">🗑</button>")
    lines.append(f"    </td>")
    lines.append("  </tr>")
    lines.append("  {% else %}")
    lines.append(f"  <tr><td colspan=\"10\" style=\"text-align:center;color:#888\">No {tplural} yet.</td></tr>")
    lines.append("  {% endfor %}")
    lines.append("  </tbody>")
    lines.append("</table>")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Plain style generators  (Post/Redirect/Get — no JavaScript)
# ---------------------------------------------------------------------------

def gen_routes_plain(tables: list[type[Table]], prefix: str) -> str:
    """Generate routes_app.py using Post/Redirect/Get — no HTMX needed."""

    fk_refs: dict[str, type[Table]] = {}
    for t in tables:
        for col in user_columns(t):
            ref = fk_ref(col)
            if ref and ref.__name__ != "BaseUser":
                fk_refs[ref.__name__] = ref

    all_tables_map = {t.__name__: t for t in tables}
    all_tables_map.update(fk_refs)
    import_names = sorted(all_tables_map.keys())

    tdir = prefix.strip("/")  # used as template subdirectory name

    lines: list[str] = []
    lines.append('"""')
    lines.append(f"Server-rendered routes — generated by scripts/scaffold_htmx.py --style plain")
    lines.append("")
    lines.append("Edit freely.  Re-run the scaffold to regenerate from scratch (use --force).")
    lines.append("")
    lines.append("Pattern: every form POSTs to a mutation endpoint which redirects back to")
    lines.append(f"GET {prefix}/ — the single page that renders everything.")
    lines.append('"""')
    lines.append("")
    lines.append("from fastapi import APIRouter, Form, Request")
    lines.append("from fastapi.responses import HTMLResponse, RedirectResponse")
    lines.append("from fastapi.templating import Jinja2Templates")
    lines.append("from piccolo.apps.user.tables import BaseUser")
    lines.append("from piccolo_api.session_auth.tables import SessionsBase")
    lines.append("from starlette.status import HTTP_303_SEE_OTHER")
    lines.append("")
    lines.append("from auth_helpers import clear_session_cookie, get_authenticated_user, set_session_cookie")
    lines.append(f"from tables import {', '.join(import_names)}")
    lines.append("")
    lines.append(f'router = APIRouter(prefix="{prefix}")')
    lines.append('templates = Jinja2Templates(directory="templates")')
    lines.append("")

    # _app_context helper
    lines.append("")
    lines.append("# ---------------------------------------------------------------------------")
    lines.append("# Shared helper")
    lines.append("# ---------------------------------------------------------------------------")
    lines.append("")
    lines.append("async def _app_context(user: BaseUser) -> dict:")
    lines.append('    """Fetch all data needed to render the page."""')
    lines.append('    ctx: dict = {"user": user}')

    added: set[str] = set()
    for ref_name in fk_refs:
        var = plural(ref_name.lower())
        lines.append(f'    ctx["{var}"] = await {ref_name}.select()')
        added.add(ref_name)

    for t in tables:
        var = plural(t.__name__.lower())
        cols = user_columns(t)
        fk_cols = [c for c in cols if fk_ref(c) and fk_ref(c).__name__ != "BaseUser"]
        user_fk_cols = [c for c in cols if fk_ref(c) and fk_ref(c).__name__ == "BaseUser"]
        if user_fk_cols:
            where_clause = f".where({t.__name__}.{col_name(user_fk_cols[0])} == user.id)"
        elif is_user_data(t, {t.__name__: t for t in tables}):
            where_clause = "  # TODO: filter by owner, e.g. .where(...)"
        else:
            where_clause = ""
        if fk_cols:
            join_args = ", ".join(f"{t.__name__}.{col_name(c)}._.name" for c in fk_cols)
            lines.append(f'    ctx["{var}"] = await {t.__name__}.select({t.__name__}.all_columns(), {join_args}){where_clause}')
        elif t.__name__ not in added:
            lines.append(f'    ctx["{var}"] = await {t.__name__}.select(){where_clause}')

    lines.append("    return ctx")
    lines.append("")

    # GET / — full page
    lines.append("")
    lines.append("# ---------------------------------------------------------------------------")
    lines.append(f"# GET {prefix}/  — renders everything on one page")
    lines.append("# ---------------------------------------------------------------------------")
    lines.append("")
    lines.append('@router.get("/", response_class=HTMLResponse)')
    lines.append("async def app_index(request: Request):")
    lines.append("    user = await get_authenticated_user(request)")
    lines.append(f'    ctx = await _app_context(user) if user else {{"user": None}}')
    lines.append(f'    return templates.TemplateResponse(request, "{tdir}/page.html", ctx)')
    lines.append("")

    # login / logout
    lines.append("")
    lines.append("# ---------------------------------------------------------------------------")
    lines.append("# Auth")
    lines.append("# ---------------------------------------------------------------------------")
    lines.append("")
    lines.append('@router.post("/login")')
    lines.append("async def app_login(request: Request, username: str = Form(...), password: str = Form(...)):")
    lines.append("    user_id = await BaseUser.login(username=username, password=password)")
    lines.append("    if not user_id:")
    lines.append("        # Re-render login page with error message")
    lines.append(f'        return templates.TemplateResponse(request, "{tdir}/page.html",')
    lines.append(f'            {{"user": None, "error": "Invalid username or password"}}, status_code=401)')
    lines.append("    session = await SessionsBase.create_session(user_id=user_id)")
    lines.append(f'    response = RedirectResponse("{prefix}/", status_code=HTTP_303_SEE_OTHER)')
    lines.append("    set_session_cookie(response=response, token=session.token)")
    lines.append("    return response")
    lines.append("")
    lines.append('@router.post("/logout")')
    lines.append("async def app_logout(request: Request):")
    lines.append('    token = request.cookies.get("id")')
    lines.append("    if token:")
    lines.append("        await SessionsBase.remove_session(token=token)")
    lines.append(f'    response = RedirectResponse("{prefix}/", status_code=HTTP_303_SEE_OTHER)')
    lines.append("    clear_session_cookie(response)")
    lines.append("    return response")
    lines.append("")

    # per-table CRUD
    owned_tables = [t for t in tables if is_user_data(t, {t.__name__: t for t in tables})]
    for t in owned_tables:
        tname = t.__name__
        tvar = tname.lower()
        tplural = plural(tvar)
        cols = user_columns(t)
        bool_cols = [c for c in cols if isinstance(c, Boolean)]
        create_cols = [c for c in cols if fk_ref(c) is None or fk_ref(c).__name__ != "BaseUser"]

        lines.append("")
        lines.append("# ---------------------------------------------------------------------------")
        lines.append(f"# {tname}")
        lines.append("# ---------------------------------------------------------------------------")
        lines.append("")

        # create
        form_params = ", ".join(
            f"{col_name(c)}: int = Form(...)" if isinstance(c, ForeignKey) else
            f"{col_name(c)}: bool = Form(False)" if isinstance(c, Boolean) else
            f"{col_name(c)}: str = Form(...)"
            for c in create_cols
        )
        new_obj_args = ", ".join(f"{col_name(c)}={col_name(c)}" for c in create_cols)
        lines.append(f'@router.post("/{tplural}")')
        lines.append(f"async def app_create_{tvar}(request: Request, {form_params}):")
        lines.append(f'    user = await get_authenticated_user(request)')
        lines.append(f'    if not user: return RedirectResponse("{prefix}/", status_code=HTTP_303_SEE_OTHER)')
        lines.append(f"    await {tname}.insert({tname}({new_obj_args}))")
        lines.append(f'    return RedirectResponse("{prefix}/", status_code=HTTP_303_SEE_OTHER)')
        lines.append("")

        # toggle — POST only (HTML forms don't support PUT/PATCH)
        for bc in bool_cols:
            bcn = col_name(bc)
            lines.append(f'@router.post("/{tplural}/{{item_id}}/toggle_{bcn}")')
            lines.append(f"async def app_toggle_{tvar}_{bcn}(request: Request, item_id: int):")
            lines.append(f'    user = await get_authenticated_user(request)')
            lines.append(f'    if not user: return RedirectResponse("{prefix}/", status_code=HTTP_303_SEE_OTHER)')
            lines.append(f"    item = await {tname}.objects().where({tname}.id == item_id).first()")
            lines.append(f"    if item:")
            lines.append(f"        await {tname}.update({{{tname}.{bcn}: not item.{bcn}}}).where({tname}.id == item_id)")
            lines.append(f'    return RedirectResponse("{prefix}/", status_code=HTTP_303_SEE_OTHER)')
            lines.append("")

        # delete — also POST (HTML forms can't DELETE)
        lines.append(f'@router.post("/{tplural}/{{item_id}}/delete")')
        lines.append(f"async def app_delete_{tvar}(request: Request, item_id: int):")
        lines.append(f'    user = await get_authenticated_user(request)')
        lines.append(f'    if not user: return RedirectResponse("{prefix}/", status_code=HTTP_303_SEE_OTHER)')
        lines.append(f"    await {tname}.delete().where({tname}.id == item_id)")
        lines.append(f'    return RedirectResponse("{prefix}/", status_code=HTTP_303_SEE_OTHER)')
        lines.append("")

    return "\n".join(lines)


def gen_page_html_plain(prefix: str) -> str:
    tdir = prefix.strip("/")
    return textwrap.dedent(f"""\
        <!DOCTYPE html>
        <html lang="en">
        <head>
          <meta charset="UTF-8" />
          <meta name="viewport" content="width=device-width, initial-scale=1.0" />
          <title>App</title>
          <!-- No JavaScript needed — this is plain HTML + server-rendered Jinja2 -->
          <style>
            body {{ font-family: sans-serif; max-width: 800px; margin: 2rem auto; padding: 0 1rem; }}
            table {{ width: 100%; border-collapse: collapse; margin-top: 1rem; }}
            th, td {{ text-align: left; padding: 0.4rem 0.6rem; border-bottom: 1px solid #ddd; }}
            th {{ background: #f4f4f4; }}
            .done {{ text-decoration: line-through; color: #888; }}
            .error {{ color: red; }}
            button {{ cursor: pointer; }}
            form.inline {{ display: inline; }}
          </style>
        </head>
        <body>
          {{% if user %}}
            {{% include "{tdir}/_app.html" %}}
          {{% else %}}
            {{% include "{tdir}/_login.html" %}}
          {{% endif %}}
        </body>
        </html>
    """)


def gen_login_html_plain(prefix: str) -> str:
    return textwrap.dedent(f"""\
        <section id="login">
          <h2>Log in</h2>
          <!-- Standard HTML form — no JavaScript -->
          <form action="{prefix}/login" method="post">
            <div>
              <label>Username<br /><input name="username" type="text" required autofocus /></label>
            </div>
            <div style="margin-top:0.5rem">
              <label>Password<br /><input name="password" type="password" required /></label>
            </div>
            <div style="margin-top:0.75rem">
              <button type="submit">Log in</button>
            </div>
            {{% if error %}}<p class="error">{{{{ error }}}}</p>{{% endif %}}
          </form>
        </section>
    """)


def gen_app_html_plain(tables: list[type[Table]], fk_refs: dict, prefix: str) -> str:
    tdir = prefix.strip("/")
    sections: list[str] = []

    sections.append('<section id="app">')
    sections.append("  <p>")
    sections.append("    Logged in as <strong>{{ user.username }}</strong>")
    sections.append(f'    <form class="inline" action="{prefix}/logout" method="post">')
    sections.append('      <button type="submit" style="margin-left:1rem">Log out</button>')
    sections.append("    </form>")
    sections.append("  </p>")
    sections.append("")

    all_tables_map = {t.__name__: t for t in tables}
    owned_tables = [t for t in tables if is_user_data(t, all_tables_map)]
    for t in owned_tables:
        tname = t.__name__
        tvar = tname.lower()
        tplural = plural(tvar)
        cols = user_columns(t)
        create_cols = [c for c in cols if fk_ref(c) is None or fk_ref(c).__name__ != "BaseUser"]

        sections.append(f"  <!-- ---- {tname} ---- -->")
        sections.append(f"  <h2>{label(tplural)}</h2>")
        sections.append("")
        sections.append(f'  <form action="{prefix}/{tplural}" method="post"')
        sections.append(f'        style="display:flex;gap:0.5rem;flex-wrap:wrap;margin-bottom:1rem">')

        for c in create_cols:
            cname = col_name(c)
            ref = fk_ref(c)
            if ref:
                ref_var = plural(ref.__name__.lower())
                sections.append(f'    <select name="{cname}" required>')
                sections.append(f"      {{% for item in {ref_var} %}}")
                sections.append(f'        <option value="{{{{ item.id }}}}">{{{{ item.name }}}}</option>')
                sections.append(f"      {{% endfor %}}")
                sections.append(f"    </select>")
            elif isinstance(c, Boolean):
                sections.append(f'    <label><input name="{cname}" type="checkbox" /> {label(cname)}</label>')
            else:
                sections.append(f'    <input name="{cname}" type="text" placeholder="{label(cname)}" required />')

        sections.append(f"    <button type=\"submit\">Add {label(tvar)}</button>")
        sections.append(f"  </form>")
        sections.append("")
        sections.append(f"  {{% include \"{tdir}/_{tvar}_table.html\" %}}")
        sections.append("")

    sections.append("</section>")
    return "\n".join(sections)


def gen_table_html_plain(t: type[Table], prefix: str) -> str:
    tname = t.__name__
    tvar = tname.lower()
    tplural = plural(tvar)
    cols = user_columns(t)
    bool_cols = [c for c in cols if isinstance(c, Boolean)]
    fk_cols = [c for c in cols if isinstance(c, ForeignKey) and fk_ref(c) and fk_ref(c).__name__ != "BaseUser"]
    display_cols = [c for c in cols if not isinstance(c, Boolean) and fk_ref(c) is None]

    lines = [f'<table id="{tvar}-table">']
    lines.append("  <thead><tr>")
    for c in display_cols:
        lines.append(f"    <th>{label(col_name(c))}</th>")
    for c in fk_cols:
        lines.append(f"    <th>{label(col_name(c))}</th>")
    for c in bool_cols:
        lines.append(f"    <th>{label(col_name(c))}</th>")
    lines.append("    <th></th>")
    lines.append("  </tr></thead>")
    lines.append("  <tbody>")
    lines.append(f"  {{% for item in {tvar}s %}}")
    lines.append("  <tr>")
    for c in display_cols:
        cname = col_name(c)
        lines.append(f"    <td>{{{{ item.{cname} }}}}</td>")
    for c in fk_cols:
        cname = col_name(c)
        lines.append(f"    <td>{{{{ item['{cname}.name'] or '\u2014' }}}}</td>")
    for c in bool_cols:
        cname = col_name(c)
        lines.append(f"    <td>")
        lines.append(f"      <form class=\"inline\" action=\"{prefix}/{tplural}/{{{{ item.id }}}}/toggle_{cname}\" method=\"post\">")
        lines.append(f"        <button type=\"submit\">{{{{ '\u2705' if item.{cname} else '\u2b1c' }}}}</button>")
        lines.append(f"      </form>")
        lines.append(f"    </td>")
    lines.append(f"    <td>")
    lines.append(f"      <form class=\"inline\" action=\"{prefix}/{tplural}/{{{{ item.id }}}}/delete\" method=\"post\">")
    lines.append(f"        <button type=\"submit\" onclick=\"return confirm('Delete this {label(tvar)}?')\">🗑</button>")
    lines.append(f"      </form>")
    lines.append(f"    </td>")
    lines.append("  </tr>")
    lines.append("  {% else %}")
    lines.append(f"  <tr><td colspan=\"10\" style=\"text-align:center;color:#888\">No {tplural} yet.</td></tr>")
    lines.append("  {% endfor %}")
    lines.append("  </tbody>")
    lines.append("</table>")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--style", default="plain", choices=["plain", "htmx"],
                        help="plain = Post/Redirect/Get, no JS (default); htmx = partial swaps")
    parser.add_argument("--prefix", default=None,
                        help="URL prefix for the router (default: /app for plain, /htmx for htmx)")
    parser.add_argument("--tables-mod", default="tables", help="Python module containing Piccolo Table subclasses")
    parser.add_argument("--out-routes", default=None, help="Output path for the routes file")
    parser.add_argument("--out-templates", default=None, help="Output directory for templates")
    parser.add_argument("--force", action="store_true", help="Overwrite existing files")
    args = parser.parse_args()

    # Apply style-dependent defaults
    is_plain = args.style == "plain"
    prefix = args.prefix or ("/app" if is_plain else "/htmx")
    tdir = prefix.strip("/")
    routes_path = Path(args.out_routes or (f"{tdir}_routes.py"))
    out_dir = Path(args.out_templates or f"templates/{tdir}")

    # Add project root to sys.path so we can import the tables module.
    sys.path.insert(0, str(Path(__file__).parent.parent))

    mod = importlib.import_module(args.tables_mod)
    tables = discover_tables(mod)

    if not tables:
        print(f"No Piccolo Table subclasses found in '{args.tables_mod}'. Nothing generated.")
        sys.exit(1)

    print(f"Style:  {args.style}")
    print(f"Prefix: {prefix}")
    print(f"Found tables: {[t.__name__ for t in tables]}")

    fk_refs: dict[str, type[Table]] = {}
    for t in tables:
        for col in user_columns(t):
            ref = fk_ref(col)
            if ref and ref.__name__ != "BaseUser":
                fk_refs[ref.__name__] = ref

    all_tables_map = {t.__name__: t for t in tables}
    owned_tables = [t for t in tables if is_user_data(t, all_tables_map)]

    out_dir.mkdir(parents=True, exist_ok=True)

    def write(path: Path, content: str):
        if path.exists() and not args.force:
            print(f"  SKIP  {path}  (already exists — use --force to overwrite)")
            return
        path.write_text(content)
        print(f"  WRITE {path}")

    if is_plain:
        write(routes_path, gen_routes_plain(tables, prefix))
        write(out_dir / "page.html", gen_page_html_plain(prefix))
        write(out_dir / "_login.html", gen_login_html_plain(prefix))
        write(out_dir / "_app.html", gen_app_html_plain(tables, fk_refs, prefix))
        for t in owned_tables:
            write(out_dir / f"_{t.__name__.lower()}_table.html", gen_table_html_plain(t, prefix))
    else:
        write(routes_path, gen_routes(tables))
        write(out_dir / "page.html", gen_page_html(tables))
        write(out_dir / "_login.html", gen_login_html())
        write(out_dir / "_app.html", gen_app_html(tables, fk_refs))
        for t in owned_tables:
            write(out_dir / f"_{t.__name__.lower()}_table.html", gen_table_html(t))

    print()
    print("Done! Next steps:")
    print(f"  1. Review {routes_path} and adjust ownership/filtering as needed.")
    print(f"  2. In app.py add:")
    print(f"       from {routes_path.stem} import router as {tdir}_router")
    print(f"       app.include_router({tdir}_router)")
    print(f"     (skip if already done)")
    print(f"  3. Run: python -m uvicorn app:app --reload")
    print(f"  4. Visit: http://localhost:8000{prefix}/")


if __name__ == "__main__":
    main()
